name: PromptProof (demo)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug - Check files
        run: |
          echo "=== Current directory ==="
          pwd
          echo "=== List files in root ==="
          ls -la
          echo "=== Check if promptproof.yaml exists ==="
          test -f promptproof.yaml && echo "✓ promptproof.yaml exists" || echo "✗ promptproof.yaml NOT found"
          echo "=== Check fixtures directory ==="
          ls -la fixtures/ || echo "fixtures directory not found"
          echo "=== Check specific fixture file ==="
          test -f fixtures/support-replies/outputs.jsonl && echo "✓ fixtures/support-replies/outputs.jsonl exists" || echo "✗ fixture file NOT found"
          echo "=== Show promptproof.yaml content (first 5 lines) ==="
          head -5 promptproof.yaml || echo "Could not read promptproof.yaml"
          echo "=== Count lines in fixture file ==="
          wc -l fixtures/support-replies/outputs.jsonl || echo "Could not count fixture lines"
      
      - name: Test CLI directly
        run: |
          echo "=== Testing PromptProof CLI directly ==="
          npx -y -p promptproof-cli@beta promptproof --version || echo "Failed to get version"
          echo "=== Running eval with CLI directly ==="
          npx -y -p promptproof-cli@beta promptproof eval -c promptproof.yaml --format json --out test-direct 2>&1 || echo "CLI eval failed"
          echo "=== Check if report was created ==="
          ls -la test-direct.* || echo "No test-direct report files found"
          if [ -f test-direct.json ]; then
            echo "=== JSON report content (first 20 lines) ==="
            head -20 test-direct.json
          fi
      
      - name: PromptProof (report-only)
        uses: geminimir/promptproof-action@main
        with:
          config: promptproof.yaml
          format: html
          mode: report-only
          report-artifact: promptproof-report
      - name: Create snapshot on success (main only)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          npx -y -p promptproof-cli@beta promptproof snapshot promptproof.yaml --promote
      
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: promptproof-report
          path: promptproof-report.*
