name: PromptProof (demo)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: PromptProof (report-only)
        uses: geminimir/promptproof-action@main
        with:
          config: promptproof.yaml
          format: html
          mode: report-only
          report-artifact: promptproof-report
      - name: Create snapshot on success (main only)
        if: github.ref == 'refs/heads/main' && success()
        run: |
          npx -y -p promptproof-cli@beta promptproof snapshot promptproof.yaml --promote
      
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: promptproof-report
          path: promptproof-report.*
