name: PromptProof (demo)
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  eval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: geminimir/promptproof-action@v0
        with:
          config: promptproof.yaml
          format: html
          mode: warn
      - name: Create snapshot on success
        if: github.ref == 'refs/heads/main' && success()
        run: |
          npx promptproof snapshot promptproof.yaml --promote
      
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: promptproof-report
          path: promptproof-report.*
